esphome:
  name: proflame2-fireplace

esp32:
  board: denky32
  framework:
    type: arduino

wifi:
  ssid: "myssidwifi"
  password: "replaceme"
  ap:
    ssid: "ProFlame2-Fallback"
    password: "fallbackme!"

logger:
  level: DEBUG

api:
  encryption:
    key: "ZZwCKz2VGE+o3T2h0yNKlxX3c9D4N5B4e+HLRjkqSzI="

spi:
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23

proflame2:
  id: my_fireplace
  cs_pin: GPIO5
  gdo0_pin: GPIO4
  serial_number: 0xAA9802

  power:
    name: "Fireplace Power"
    icon: "mdi:fireplace"

  pilot:
    name: "Fireplace Pilot Mode"
    icon: "mdi:fire"
    entity_category: config

  aux:
    name: "Fireplace Aux Power"
    icon: "mdi:power-plug"

  flame:
    name: "Fireplace Flame Height"
    icon: "mdi:fire"
    unit_of_measurement: ""
    mode: slider

  fan:
    name: "Fireplace Fan Speed"
    icon: "mdi:fan"
    unit_of_measurement: ""
    mode: slider

sensor:
  - platform: wifi_signal
    name: "Fireplace WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Fireplace Uptime"

binary_sensor:
  - platform: status
    name: "Fireplace Connection Status"

button:
  - platform: restart
    name: "Fireplace Controller Restart"
    icon: "mdi:restart"

text_sensor:
  - platform: version
    name: "Fireplace ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "Fireplace IP Address"
    ssid:
      name: "Fireplace Connected SSID"

web_server:
  port: 80
  auth:
    username: admin
    password: "adminpassword"

time:
  - platform: homeassistant
    id: homeassistant_time

